### YML CONFIGURATION FILE ###

# PC Side connection #
host_pc: "localhost"
comm_port: 8000
video_port: 7000
video2_port: 7001

# PLC_Side_connection #
host_plc: "192.168.0.241" 
plc_port_1: 2000
plc_port_2: 2001

# Camera IDs #
footage_cam_ID: 1
AI_cam_ID: 1

